# Generated by Django 4.2.16 on 2025-01-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='register_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
