# Generated by Django 4.2.16 on 2025-01-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announce_register_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
