version: "3.9"

services:
  frontend:
    image: registry.gitlab.com/ahsan7211007/ahsan-web-salepage:dev-20241122
    container_name: ahsan-web-salepage
    ports:
      - "80:80"

  backend:
    build:
      context: .
    container_name: ahsan-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - frontend
