version: "3.9"

services:
  frontend:
    image: registry.gitlab.com/ahsan7211007/ahsan-web:latest
    container_name: frontend
    ports:
      - "80:80"

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
