version: "3.9"

services:
  frontend:
    image: ahsanfrontend
    container_name: ahsan-web-salepage-front
    ports:
      - "80:80"

  backend:
    build:
      context: .
    container_name: ahsan-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - frontend
