version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: ahsan-db
    environment:
      MYSQL_DATABASE: ahsantrust
      MYSQL_ROOT_PASSWORD: readnrecharge123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    image: ahsanfrontend
    container_name: ahsan-web-salepage-front
    ports:
      - "80:80"

  backend:
    build:
      context: .
    container_name: ahsan-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata:
