version: '3.9'
services:
  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    image: nureman/deploylab-backend:latest
    ports:
      - "8080:8080"
    networks:
      - frontend-backend-net
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=ahsantrust
      - MYSQL_USER=root
      - MYSQL_PASSWORD=readnrecharge123

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: readnrecharge123
      MYSQL_DATABASE: ahsantrust
      MYSQL_USER: root
      MYSQL_PASSWORD: readnrecharge123
    ports:
      - "3306:3306"

