# Generated by Django 4.2.16 on 2024-09-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_rename_stores_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('categories', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('values', models.JSONField(blank=True, default=list)),
                ('qualities', models.JSONField(blank=True, default=list)),
                ('ethics', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
        ),
    ]
