# Generated by Django 5.0.7 on 2024-08-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
