# Generated by Django 5.0.7 on 2024-08-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, max_length=500, upload_to=""),
        ),
    ]
