# Generated by Django 5.0.7 on 2024-08-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
