# Generated by Django 5.0.7 on 2024-08-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="details",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
