# Generated by Django 5.0.7 on 2024-07-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("images_url", models.URLField(blank=True)),
                ("details", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=50)),
                ("categories", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("time", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
