# Generated by Django 5.0.7 on 2024-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_stores_details_alter_stores_images_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="stores",
            name="ActiveDate",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stores",
            name="benefits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="stores",
            name="ethics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="stores",
            name="facebook",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stores",
            name="instagram",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="stores",
            name="logo",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="stores",
            name="qualities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="stores",
            name="values",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
