# Generated by Django 4.2.16 on 2024-09-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_stores_activedate_stores_benefits_stores_ethics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='Product_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
