# Generated by Django 4.2.16 on 2025-04-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_rename_stores_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
